### ISSUE TITLE
¿ Hay inconsistencia de fechas entre Adela, CKAN y ng-ckan ?

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/shogun#41]
Voy a usar de ejemplo el [Plan de Apertura de HGGEA](http://busca.datos.gob.mx/#!/conjuntos/plan-de-apertura-institucional-de-hggea)

* En ng-ckan se ve así

![plan-apertura-hggea-ng-ckan](https://cloud.githubusercontent.com/assets/2633527/12899592/9d6ae274-ce77-11e5-9cd8-fb9488e61373.png)

* En ckan están estas fechas  ( [ver detalle en ckan](http://catalogo.datos.gob.mx/api/3/action/package_show?id=plan-de-apertura-institucional-de-hggea) )
```
"metadata_created": "2015-10-26T23:20:40.833526",
"metadata_modified": "2016-02-08T18:09:56.913238"
extras": [
{
    "key": "dcat_modified",
    "value": "2015-10-20T10:53:02.000Z"
},
```

* Y finalmente en Adela nos dice esto ( [ver detalle en adela](http://adela.datos.gob.mx/hggea/catalogo.json) )
```
"modified": "2015-11-28T00:17:09.000Z",
```

* ¿Cómo se debería ver en ng-ckan?
* ¿Por qué en ng-ckan tenemos `Última actualización`  y  `Fecha de última modificación de los datos`? 
* Esa fecha de `modified` en Adela ¿A cuál corressponde en CKAN?

**Comment by carlosmaya** [comment]
@chuckcfs  creo que en ng-ckan la relación debería ser

```
Registro en el sitio   =>  metadata_created
Fecha de última modificación de los datos  =>  dcat_modified
```

**Comment by chuckcfs** [comment]
@carlosmaya y quitamos la `Última actualización`?

**Comment by carlosmaya** [comment]
ya vi, más bien deberíamos quitar `Fecha de última modificación de los datos` y dejar `Última actualización`

**Comment by carlosmaya** [comment]
@urkonn en CKAN ¿Cuál es la diferencia entre `metadata_modified` y el `dcat_modified` que está en los extras?

**Comment by carlosmaya** [comment]
se cerró con mxabierto/ng-ckan#265
